using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Configuration;
using NuGet.ContentModel;
using static Microsoft.AspNetCore.Razor.Language.TagHelperMetadata;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using static NuGet.Packaging.PackagingConstants;
using static System.Net.Mime.MediaTypeNames;
using System.Collections.Generic;
using System.Composition;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Threading;
using System;

namespace FinanceAPI.Models
{
    public static class Icons
    {
        public static List<dynamic> GetIcones()
        {
            return new List<dynamic>()
            {
                new { Label = "Idoso", Value = "po-icon po-icon-a11y-elderly" },
                new { Label = "Grávida", Value = "po-icon po-icon-a11y-pregnant" },
                new { Label = "Cadeira de Rodas", Value = "po-icon po-icon-a11y-wheelchair" },
                new { Label = "Agro", Value = "po-icon po-icon-agro-business" },
                new { Label = "Centralizar", Value = "po-icon po-icon-align-center" },
                new { Label = "Justificar", Value = "po-icon po-icon-align-justify" },
                new { Label = "Alinhar à esquerda", Value = "po-icon po-icon-align-left" },
                new { Label = "Alinhar à direita", Value = "po-icon po-icon-align-right" },
                new { Label = "Âncora", Value = "po-icon po-icon-anchor" },
                new { Label = "Arquivo", Value = "po-icon po-icon-archive" },
                new { Label = "Seta para baixo", Value = "po-icon po-icon-arrow-down" },
                new { Label = "Seta para esquerda", Value = "po-icon po-icon-arrow-left" },
                new { Label = "Seta para direita", Value = "po-icon po-icon-arrow-right" },
                new { Label = "Seta para cima", Value = "po-icon po-icon-arrow-up" },
                new { Label = "Anexo", Value = "po-icon po-icon-attach" },
                new { Label = "Barreira Automática", Value = "po-icon po-icon-automatic-barrier" },
                new { Label = "Balança", Value = "po-icon po-icon-balance" },
                new { Label = "Balança de peso", Value = "po-icon po-icon-balance-weight" },
                new { Label = "Código de Barras", Value = "po-icon po-icon-bar-code" },
                new { Label = "Basquete", Value = "po-icon po-icon-basket" },
                new { Label = "Bluetooth", Value = "po-icon po-icon-bluetooth" },
                new { Label = "Livro", Value = "po-icon po-icon-book" },
                new { Label = "Calculadora", Value = "po-icon po-icon-calculator" },
                new { Label = "Calendário", Value = "po-icon po-icon-calendar" },
                new { Label = "Calendário OK", Value = "po-icon po-icon-calendar-ok" },
                new { Label = "Calendário Cfg", Value = "po-icon po-icon-calendar-settings" },
                new { Label = "Câmera", Value = "po-icon po-icon-camera" },
                new { Label = "Cartão", Value = "po-icon po-icon-cart" },
                new { Label = "Troca", Value = "po-icon po-icon-change" },
                new { Label = "Gráfico de Área", Value = "po-icon po-icon-chart-area" },
                new { Label = "Gráfico de Colunas", Value = "po-icon po-icon-chart-columns" },
                new { Label = "Gráfico", Value = "po-icon po-icon-chat" },
                new { Label = "Limpar Contéudo", Value = "po-icon po-icon-clear-content" },
                new { Label = "Prancheta", Value = "po-icon po-icon-clipboard" },
                new { Label = "Relógio", Value = "po-icon po-icon-clock" },
                new { Label = "Fechar", Value = "po-icon po-icon-close" },
                new { Label = "Empresa", Value = "po-icon po-icon-company" },
                new { Label = "Construção", Value = "po-icon po-icon-construction" },
                new { Label = "Copia", Value = "po-icon po-icon-copy" },
                new { Label = "Algodão", Value = "po-icon po-icon-cotton" },
                new { Label = "Pagamento no crédito", Value = "po-icon po-icon-credit-payment" },
                new { Label = "Cortar", Value = "po-icon po-icon-cut" },
                new { Label = "Banco de dados", Value = "po-icon po-icon-database" },
                new { Label = "Pagamento no débito", Value = "po-icon po-icon-debit-payment" },
                new { Label = "Deletar", Value = "po-icon po-icon-delete" },
                new { Label = "Desktop", Value = "po-icon po-icon-device-desktop" },
                new { Label = "Notebook", Value = "po-icon po-icon-device-notebook" },
                new { Label = "Smartphone", Value = "po-icon po-icon-device-smartphone" },
                new { Label = "Tablet", Value = "po-icon po-icon-device-tablet" },
                new { Label = "Arquivo XLS", Value = "po-icon po-icon-doc-xls" },
                new { Label = "Documento", Value = "po-icon po-icon-document" },
                new { Label = "Cópia de documento", Value = "po-icon po-icon-document-double" },
                new { Label = "Documento preenchido", Value = "po-icon po-icon-document-filled" },
                new { Label = "Download", Value = "po-icon po-icon-download" },
                new { Label = "Editar", Value = "po-icon po-icon-edit" },
                new { Label = "Exame", Value = "po-icon po-icon-exam" },
                new { Label = "Exclamação", Value = "po-icon po-icon-exclamation" },
                new { Label = "Sair", Value = "po-icon po-icon-exit" },
                new { Label = "Exportar", Value = "po-icon po-icon-export" },
                new { Label = "Olho", Value = "po-icon po-icon-eye" },
                new { Label = "Olho fechado", Value = "po-icon po-icon-eye-off" },
                new { Label = "Filtro", Value = "po-icon po-icon-filter" },
                new { Label = "Finanças", Value = "po-icon po-icon-finance" },
                new { Label = "Bitcoin", Value = "po-icon po-icon-finance-bitcoin" },
                new { Label = "Finanças seguras", Value = "po-icon po-icon-finance-secure" },
                new { Label = "Primeira página", Value = "po-icon po-icon-first-page" },
                new { Label = "Pasta", Value = "po-icon po-icon-folder" },
                new { Label = "Comida", Value = "po-icon po-icon-food" },
                new { Label = "Cardápio", Value = "po-icon po-icon-food-menu" },
                new { Label = "Gasolina", Value = "po-icon po-icon-gas" },
                new { Label = "Presente", Value = "po-icon po-icon-gift" },
                new { Label = "Grade", Value = "po-icon po-icon-grid" },
                new { Label = "Aperto de mão", Value = "po-icon po-icon-handshake" },
                new { Label = "Disco Rígido", Value = "po-icon po-icon-hdd" },
                new { Label = "Ajuda", Value = "po-icon po-icon-help" },
                new { Label = "Histórico", Value = "po-icon po-icon-history" },
                new { Label = "Casa", Value = "po-icon po-icon-home" },
                new { Label = "Alinhar-in-line", Value = "po-icon po-icon-image-align-inline" },
                new { Label = "Alinha a esquerda", Value = "po-icon po-icon-image-align-left" },
                new { Label = "Alinha a direita", Value = "po-icon po-icon-image-align-right" },
                new { Label = "Informação", Value = "po-icon po-icon-info" },
                new { Label = "Injetor", Value = "po-icon po-icon-injector" },
                new { Label = "Teclado", Value = "po-icon po-icon-keyboard" },
                new { Label = "Última página", Value = "po-icon po-icon-last-page" },
                new { Label = "Camadas", Value = "po-icon po-icon-layers" },
                new { Label = "Luz", Value = "po-icon po-icon-light" },
                new { Label = "Gostou", Value = "po-icon po-icon-like" },
                new { Label = "Link", Value = "po-icon po-icon-link" },
                new { Label = "Lista", Value = "po-icon po-icon-list" },
                new { Label = "Trancado", Value = "po-icon po-icon-lock" },
                new { Label = "Destrancado", Value = "po-icon po-icon-lock-off" },
                new { Label = "E-mail", Value = "po-icon po-icon-mail" },
                new { Label = "Manofatura", Value = "po-icon po-icon-manufacture" },
                new { Label = "Mapa", Value = "po-icon po-icon-map" },
                new { Label = "Menu", Value = "po-icon po-icon-menu" },
                new { Label = "Fechar menu", Value = "po-icon po-icon-menu-close" },
                new { Label = "Abrir Menu", Value = "po-icon po-icon-menu-open" },
                new { Label = "Mensagem", Value = "po-icon po-icon-message" },
                new { Label = "Microfone", Value = "po-icon po-icon-microphone" },
                new { Label = "Menos", Value = "po-icon po-icon-minus" },
                new { Label = "Menos redondo", Value = "po-icon po-icon-minus-circle" },
                new { Label = "Dinheiro", Value = "po-icon po-icon-money" },
                new { Label = "Mais", Value = "po-icon po-icon-more" },
                new { Label = "Mais vertical", Value = "po-icon po-icon-more-vert" },
                new { Label = "Novidades", Value = "po-icon po-icon-news" },
                new { Label = "Sinal", Value = "po-icon po-icon-no-signal" },
                new { Label = "Notificação", Value = "po-icon po-icon-notification" },
                new { Label = "Óleo", Value = "po-icon po-icon-oil" },
                new { Label = "Análise de Óleo", Value = "po-icon po-icon-oil-analysis" },
                new { Label = "OK", Value = "po-icon po-icon-ok" },
                new { Label = "Pallet Cheio", Value = "po-icon po-icon-pallet-full" },
                new { Label = "Pallet Parcial", Value = "po-icon po-icon-pallet-partial" },
                new { Label = "Parâmetro", Value = "po-icon po-icon-parameters" },
                new { Label = "Colar", Value = "po-icon po-icon-paste" },
                new { Label = "Pagamento", Value = "po-icon po-icon-payment" },
                new { Label = "PDF", Value = "po-icon po-icon-pdf" },
                new { Label = "Pegar", Value = "po-icon po-icon-picker" },
                new { Label = "Figura", Value = "po-icon po-icon-picture" },
                new { Label = "Fixar", Value = "po-icon po-icon-pin" },
                new { Label = "Pix", Value = "po-icon po-icon-pix-logo" },
                new { Label = "Mais", Value = "po-icon po-icon-plus" },
                new { Label = "Mais redondo", Value = "po-icon po-icon-plus-circle" },
                new { Label = "Imprimir", Value = "po-icon po-icon-print" },
                new { Label = "Colocar cartão", Value = "po-icon po-icon-pushcart" },
                new { Label = "QR Code", Value = "po-icon po-icon-qr-code" },
                new { Label = "Atualizar", Value = "po-icon po-icon-refresh" },
                new { Label = "Venda", Value = "po-icon po-icon-sale" },
                new { Label = "Tela Cheia", Value = "po-icon po-icon-screen-full" },
                new { Label = "Tela Minimizada", Value = "po-icon po-icon-screen-minimize" },
                new { Label = "Buscar", Value = "po-icon po-icon-search" },
                new { Label = "Segurança", Value = "po-icon po-icon-security-guard" },
                new { Label = "Servidor", Value = "po-icon po-icon-server" },
                new { Label = "Configurações", Value = "po-icon po-icon-settings" },
                new { Label = "Compartilhar", Value = "po-icon po-icon-share" },
                new { Label = "Sinal", Value = "po-icon po-icon-signal" },
                new { Label = "SMS", Value = "po-icon po-icon-sms" },
                new { Label = "Github", Value = "po-icon po-icon-social-github" },
                new { Label = "Instagram", Value = "po-icon po-icon-social-instagram" },
                new { Label = "Twitter", Value = "po-icon po-icon-social-twitter" },
                new { Label = "Whatsapp", Value = "po-icon po-icon-social-whatsapp" },
                new { Label = "Ordenar", Value = "po-icon po-icon-sort" },
                new { Label = "Ord.Crescente", Value = "po-icon po-icon-sort-asc" },
                new { Label = "Ord.Ascendente", Value = "po-icon po-icon-sort-ascending" },
                new { Label = "Ord.Decrescente", Value = "po-icon po-icon-sort-desc" },
                new { Label = "Ord.Descendente", Value = "po-icon po-icon-sort-descending" },
                new { Label = "Estrela", Value = "po-icon po-icon-star" },
                new { Label = "Estrela Cheia", Value = "po-icon po-icon-star-filled" },
                new { Label = "Estrela Parcial", Value = "po-icon po-icon-star-half" },
                new { Label = "Volante", Value = "po-icon po-icon-steering-wheel" },
                new { Label = "Estoque", Value = "po-icon po-icon-stock" },
                new { Label = "Tabela", Value = "po-icon po-icon-table" },
                new { Label = "Alvo", Value = "po-icon po-icon-target" },
                new { Label = "Telefone", Value = "po-icon po-icon-telephone" },
                new { Label = "Negrito", Value = "po-icon po-icon-text-bold" },
                new { Label = "Itálico", Value = "po-icon po-icon-text-italic" },
                new { Label = "Sublinhado", Value = "po-icon po-icon-text-underline" },
                new { Label = "Touch", Value = "po-icon po-icon-touch" },
                new { Label = "Viagem", Value = "po-icon po-icon-travel" },
                new { Label = "Caminhão", Value = "po-icon po-icon-truck" },
                new { Label = "Upload", Value = "po-icon po-icon-upload" },
                new { Label = "Upload na Nuvem", Value = "po-icon po-icon-upload-cloud" },
                new { Label = "Usuário", Value = "po-icon po-icon-user" },
                new { Label = "Adicionar Usuário", Value = "po-icon po-icon-user-add" },
                new { Label = "Deletar Usuário", Value = "po-icon po-icon-user-delete" },
                new { Label = "Usuários", Value = "po-icon po-icon-users" },
                new { Label = "Vídeo chamada", Value = "po-icon po-icon-video-call" },
                new { Label = "Garçonete", Value = "po-icon po-icon-waiter" },
                new { Label = "Carteira", Value = "po-icon po-icon-wallet" },
                new { Label = "Armazém", Value = "po-icon po-icon-warehouse" },
                new { Label = "Aviso", Value = "po-icon po-icon-warning" },
                new { Label = "Peso", Value = "po-icon po-icon-weight" },
                new { Label = "Mundo", Value = "po-icon po-icon-world" },
                new { Label = "XML", Value = "po-icon po-icon-xml" },
                new { Label = "Zoom In", Value = "po-icon po-icon-zoom-in" },
                new { Label = "Zoom Out", Value = "po-icon po-icon-zoom-out" },
            };

        }
    }
}
